[tox]
env_list = lint,typecheck,py311,py312,py313,py314,docs,build
requires =
    tox>=4.0
    tox-uv>=1.16

[testenv]
runner = uv-venv-lock-runner
extras = tests
commands = pytest {posargs}

[testenv:lint]
runner = uv-venv-lock-runner
extras = dev
commands = ruff check src tests examples

[testenv:typecheck]
runner = uv-venv-lock-runner
extras = typing
commands = mypy src

[testenv:docs]
runner = uv-venv-lock-runner
extras = docs
commands = sphinx-build -b html docs docs/_build/html

[testenv:build]
runner = uv-venv-lock-runner
extras =
commands = uv build
