"""Generate the committed Sourcey Python API reference from public source modules."""

from __future__ import annotations

import argparse
import ast

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages/vendor-fabric/src/vendor_fabric"
OUTPUT = ROOT / "docs/reference/api.md"


def public_members(path: Path) -> list[tuple[str, str, str, str]]:
    """Return public classes and functions declared directly by one module."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, UnicodeDecodeError, SyntaxError) as error:
        raise RuntimeError(f"Unable to parse public API source {path}: {error}") from error
    members: list[tuple[str, str, str, str]] = []
    for node in tree.body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            kind = "class" if isinstance(node, ast.ClassDef) else "function"
            signature = ""
            if not isinstance(node, ast.ClassDef):
                signature = ast.unparse(node.args)
            summary = (ast.get_docstring(node) or "No module-local docstring is available.").split("\n", 1)[0]
            members.append((kind, node.name, signature, summary))
    return members


def module_name(path: Path) -> str:
    """Map a source path to its importable dotted module name."""
    relative = path.relative_to(SOURCE).with_suffix("")
    parts = list(relative.parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(["vendor_fabric", *parts])


def render() -> str:
    """Render a deterministic, Sourcey-consumable overview of public Python APIs."""
    lines = [
        "---",
        "title: Python API reference",
        "description: Generated from public classes and functions in the vendor_fabric source tree.",
        "---",
        "",
        "This file is generated by `scripts/generate_api_reference.py`. Do not edit it by hand.",
        "Docstrings and type signatures in the Python source remain authoritative.",
        "",
    ]
    for path in sorted(SOURCE.rglob("*.py")):
        if path.name.startswith("_") and path.name != "__init__.py":
            continue
        members = public_members(path)
        if not members:
            continue
        name = module_name(path)
        lines.extend([f"## `{name}`", ""])
        for kind, member, signature, summary in members:
            if kind == "class":
                lines.append(f"### class `{member}`")
            else:
                lines.append(f"### `{member}({signature})`")
            lines.extend(["", summary, ""])
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    """Write the reference or report whether the committed output is current."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the committed reference is stale")
    args = parser.parse_args()
    try:
        content = render()
    except RuntimeError as error:
        raise SystemExit(str(error)) from error
    if args.check:
        return 0 if OUTPUT.is_file() and OUTPUT.read_text(encoding="utf-8") == content else 1
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
